In [8]:
%run poetry_gen.py --mode train

0/3350 (epoch 0) | train_loss 8.006
model saved to log/model.ckpt
669/3350 (epoch 0) | train_loss 6.305
1000/3350 (epoch 1) | train_loss 5.525
model saved to log/model.ckpt
1339/3350 (epoch 1) | train_loss 6.074
2000/3350 (epoch 2) | train_loss 5.784
model saved to log/model.ckpt
2009/3350 (epoch 2) | train_loss 6.065
2679/3350 (epoch 3) | train_loss 5.953
3000/3350 (epoch 4) | train_loss 5.596
model saved to log/model.ckpt
3349/3350 (epoch 4) | train_loss 5.859
model saved to log/model.ckpt

None


In [24]:
%run poetry_gen.py --mode sample --head 滑头小妖牛逼

INFO:tensorflow:Restoring parameters from log/model.ckpt-3350
生成藏头诗 --->  滑头小妖牛逼
滑客先遗始，头台帝自心。小阳清几日未分，妖邑忆风怀易传。牛前每自推醒卷，逼客有兵枫云声。


In [11]:
import argparse
import sys
import os
import io
import importlib
import time
import numpy as np
import collections
import tensorflow as tf
import tensorflow.contrib.rnn as rnn
import tensorflow.contrib.legacy_seq2seq as seq2seq

In [19]:
#help(collections.Counter)
c = collections.Counter('abcdeabcdabcaba')  
c.items()    

dict_items([('b', 4), ('c', 3), ('a', 5), ('e', 1), ('d', 2)])

In [43]:
a = (1,2,3) + ('a',)
{i:j for i,j in enumerate(a) }

b = [4,5,6]
display(b[:-1])
b[:-1] = [7,8,9]
b

[4, 5]

[7, 8, 9, 6]

In [11]:
%run poetry_gen.py --mode train

['^绵绢，割两耳，只有面。$',
 '^桑条韦也，女时韦也乐。$',
 '^欲得命通，问瑝嵎都雍。$',
 '^斋钟动也，和尚不上堂。$',
 '^子母相去离，连台拗倒。$',
 '^势如连璧友，心似臭兰人。$',
 '^不缘朝阙去，好此结茅庐。$',
 '^鱼戏莲叶间，参差隐叶扇。$',
 '^神羊既不触，夕鸟欲依人。$',
 '^整巾千嶂耸，曳履百泉鸣。$',
 '^清清江潭树，日夕增所思。$',
 '^人家在仙掌，云气欲生衣。$',
 '^初程莫早发，且宿灞桥头。$',
 '^素练风霜起，苍鹰画作殊。$',
 '^熊踞庭中树，龙蒸栋里云。$',
 '^省署开文苑，沧浪学钓翁。$',
 '^他乡生白发，旧国有青山。$',
 '^情人共惆怅，良友不同游。$',
 '^台笠冒山雨，渚田耕荇花。$',
 '^诗书入京国，旌旆过乡关。$',
 '^夫子生知者，相期妙理中。$',
 '^谁云隼旟吏，长对虎头岩。$',
 '^但虑彩色污，无虞臂胛肥。$',
 '^夜入真珠室，朝游玳瑁宫。$',
 '^地甃如拳石，溪横似叶舟。$',
 '^积高依郡城，迥拔凌霄汉。$',
 '^入门池色静，登阁雨声来。$',
 '^绿迸穿篱笋，红飘隔户花。$',
 '^吟倚雨残树，月收山下村。$',
 '^河势昆仑远，山形菡萏秋。$',
 '^万里岐路多，一身天地窄。$',
 '^南浦花临水，东楼月映风。$',
 '^水光先见月，露气早知秋。$',
 '^雾纹斑似豹，水力健如龙。$',
 '^塞鸿先秋去，边草入夏生。$',
 '^项斯逢水部，谁道不关情。$',
 '^成都十万户，抛若一鸿毛。$',
 '^我本南山凤，岂同凡鸟群。$',
 '^海曙云浮日，江遥水合天。$',
 '^吾家九叶相，尽继明时出。$',
 '^篆经千古涩，影泻一堂寒。$',
 '^鱼戏莲叶间，参差隐叶扇。$',
 '^君恩秋后叶，日日向人疏。$',
 '^独来成怅望，不去泥栏干。$',
 '^远来朝凤阙，归去恋元侯。$',
 '^仕宦类商贾，终日常东西。$',
 '^护犊横身立，逢人揭尾跳。$',
 '^积霭沈诸壑，微阳在半峰。$',
 '^伴行惟瘦鹤，寻步入深云。$',
 '^晓厨烹淡菜，春杼种橦花。$',
 '^扫石云随帚，耕山鸟傍人。$',
 '^轮中别有物，光外更无空。$',
 '^坐落千门日，吟残午夜灯。$'

INFO:tensorflow:Restoring parameters from log/model.ckpt-3350


'X'

(64, 14)

array([[   2, 1227, 3000,    0, 2252,  253, 1002,    0,  282,   13,  536,
           1,    3, 3000],
       [   2,  745,  485, 2192,  907,    0,  335,   22, 2192,  907,  270,
           1,    3, 3000],
       [   2,  103,   48,  494,  297,    0,  231, 3000, 3000,  527, 1950,
           1,    3, 3000],
       [   2,  667,  431,  256,  907,    0,  279,  411,    4,   19,  329,
           1,    3, 3000],
       [   2,   74, 1085,   24,   38,  157,    0,  224,  166, 3000, 1062,
           1,    3, 3000],
       [   2,  783,   35,  224, 1599, 1007,    0,   29,  140, 3000,  364,
           5,    1,    3],
       [   2,    4,  561,   77,  496,   38,    0,  223,   42,  423,  843,
         943,    1,    3],
       [   2,  301, 1226,  530,  142,  165,    0,  770,  854,  383,  142,
         977,    1,    3],
       [   2,  232, 1222,  748,    4, 1249,    0,  268,  153,  103,  274,
           5,    1,    3],
       [   2, 1761,  964,   64, 1521, 1728,    0, 1766, 1124,  191,  213,
         281,    

'Embedding'

(3001, 128)

array([[-0.61786443, -0.07709629, -0.12532227, ...,  0.5193349 ,
         0.1503872 , -0.12355197],
       [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
         0.23316611, -0.07840608],
       [ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
        -0.10131865,  0.26164633],
       ...,
       [ 0.15059002, -0.2705143 , -0.3868205 , ..., -0.01080665,
        -0.3366271 , -0.03618184],
       [ 0.00977281,  0.0544528 ,  0.00349314, ..., -0.20772688,
         0.2347655 ,  0.15280132],
       [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
         0.23684055,  0.22182734]], dtype=float32)

'Input'

(64, 14, 128)

array([[[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.04087897,  0.30896908,  0.17274971, ..., -0.109882  ,
          0.31141537,  0.05277839],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
          0.23316611, -0.07840608],
        [ 0.9782146 , -0.9526181 , -0.42369497, ..., -0.5015902 ,
         -1.3130728 ,  1.0298895 ],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734]],

       [[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.24687326,  0.03297674,  0.40071034, ..., -0.03007145,
         -0.12745138, -0.00725536],
        [-0.00508994, -0.25352705, -0.17305233, ...,  0.11986811,
         -0.17352395,  0.0735866 ],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  

'Outputs'

(896, 128)

array([[ 2.8821200e-01, -7.7424444e-02,  2.1968849e-03, ...,
         7.7774912e-02, -7.5627065e-01,  6.9714284e-01],
       [ 1.4061834e-04, -1.7498613e-03,  2.0904611e-03, ...,
         2.0755129e-03, -1.7033662e-01, -5.1412087e-02],
       [ 9.4901645e-07, -7.7243305e-05,  6.0190614e-03, ...,
         1.2217755e-01, -5.3384262e-01, -3.6002748e-02],
       ...,
       [ 7.4883407e-01, -9.9319690e-01, -2.6691213e-04, ...,
         2.1271660e-06, -9.3184143e-01, -8.2195550e-01],
       [ 1.7782239e-02, -6.8808764e-01, -6.1757069e-05, ...,
         1.7829709e-05, -9.9378151e-01, -1.4555188e-02],
       [ 7.3021853e-01, -9.8106200e-01, -4.1343910e-03, ...,
         3.5174916e-04, -9.9915051e-01, -7.5816858e-01]], dtype=float32)

'初始state'

(64, 512)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

'逻辑'

(896, 3001)

array([[  0.3890362 ,  -0.825235  ,  -7.3335123 , ...,  -5.2433887 ,
         -2.0094223 ,   4.1051226 ],
       [  1.8353196 ,  -3.3688426 ,  -5.8265133 , ...,  -3.8498738 ,
         -1.868614  ,   4.535734  ],
       [  0.47486326,  -4.431116  ,  -7.656597  , ...,  -4.7251415 ,
         -2.7518206 ,   4.3799653 ],
       ...,
       [  7.735502  ,  12.71295   , -11.42602   , ...,  -3.2191327 ,
         -2.1455696 ,   5.025229  ],
       [ -0.6715446 ,   0.05890182,  -8.282465  , ...,  -3.7530177 ,
         -2.1853254 ,   4.070532  ],
       [  5.640621  ,   5.084725  , -17.959644  , ...,  -8.8376255 ,
         -6.168395  ,   9.651815  ]], dtype=float32)

'最终状态'

(64, 512)

array([[ 2.39459085e+00, -1.95080185e+00, -1.95027947e-01, ...,
         6.95285329e-04, -1.20315105e-01, -8.66162628e-02],
       [ 1.52507639e+00, -1.92951059e+00, -3.99303716e-03, ...,
         1.44839578e-04, -4.26144786e-02, -3.70901451e-02],
       [ 1.67852080e+00, -1.93122721e+00, -4.05135052e-03, ...,
         1.68477884e-04, -3.53038050e-02, -4.80397381e-02],
       ...,
       [ 2.03748488e+00, -9.53484893e-01, -2.65403534e-04, ...,
         2.42490714e-04, -9.99338210e-01, -7.56402731e-01],
       [ 2.39980412e+00, -9.54525054e-01, -3.89187690e-03, ...,
         2.08045487e-04, -9.98932064e-01, -7.57175386e-01],
       [ 1.57792401e+00, -9.52326238e-01, -5.49907796e-04, ...,
         3.51749157e-04, -9.99150515e-01, -7.58168578e-01]], dtype=float32)

'X'

(64, 14)

array([[   2, 1227, 3000,    0, 2252,  253, 1002,    0,  282,   13,  536,
           1,    3, 3000],
       [   2,  745,  485, 2192,  907,    0,  335,   22, 2192,  907,  270,
           1,    3, 3000],
       [   2,  103,   48,  494,  297,    0,  231, 3000, 3000,  527, 1950,
           1,    3, 3000],
       [   2,  667,  431,  256,  907,    0,  279,  411,    4,   19,  329,
           1,    3, 3000],
       [   2,   74, 1085,   24,   38,  157,    0,  224,  166, 3000, 1062,
           1,    3, 3000],
       [   2,  783,   35,  224, 1599, 1007,    0,   29,  140, 3000,  364,
           5,    1,    3],
       [   2,    4,  561,   77,  496,   38,    0,  223,   42,  423,  843,
         943,    1,    3],
       [   2,  301, 1226,  530,  142,  165,    0,  770,  854,  383,  142,
         977,    1,    3],
       [   2,  232, 1222,  748,    4, 1249,    0,  268,  153,  103,  274,
           5,    1,    3],
       [   2, 1761,  964,   64, 1521, 1728,    0, 1766, 1124,  191,  213,
         281,    

'Embedding'

(3001, 128)

array([[-0.61786443, -0.07709629, -0.12532227, ...,  0.5193349 ,
         0.1503872 , -0.12355197],
       [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
         0.23316611, -0.07840608],
       [ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
        -0.10131865,  0.26164633],
       ...,
       [ 0.15059002, -0.2705143 , -0.3868205 , ..., -0.01080665,
        -0.3366271 , -0.03618184],
       [ 0.00977281,  0.0544528 ,  0.00349314, ..., -0.20772688,
         0.2347655 ,  0.15280132],
       [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
         0.23684055,  0.22182734]], dtype=float32)

'Input'

(64, 14, 128)

array([[[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.04087897,  0.30896908,  0.17274971, ..., -0.109882  ,
          0.31141537,  0.05277839],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
          0.23316611, -0.07840608],
        [ 0.9782146 , -0.9526181 , -0.42369497, ..., -0.5015902 ,
         -1.3130728 ,  1.0298895 ],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734]],

       [[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.24687326,  0.03297674,  0.40071034, ..., -0.03007145,
         -0.12745138, -0.00725536],
        [-0.00508994, -0.25352705, -0.17305233, ...,  0.11986811,
         -0.17352395,  0.0735866 ],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  

'Outputs'

(896, 128)

array([[ 2.8821200e-01, -7.7424444e-02,  2.1968849e-03, ...,
         7.7774912e-02, -7.5627065e-01,  6.9714284e-01],
       [ 1.4061834e-04, -1.7498613e-03,  2.0904611e-03, ...,
         2.0755129e-03, -1.7033662e-01, -5.1412087e-02],
       [ 9.4901645e-07, -7.7243305e-05,  6.0190614e-03, ...,
         1.2217755e-01, -5.3384262e-01, -3.6002748e-02],
       ...,
       [ 7.4883407e-01, -9.9319690e-01, -2.6691213e-04, ...,
         2.1271660e-06, -9.3184143e-01, -8.2195550e-01],
       [ 1.7782239e-02, -6.8808764e-01, -6.1757069e-05, ...,
         1.7829709e-05, -9.9378151e-01, -1.4555188e-02],
       [ 7.3021853e-01, -9.8106200e-01, -4.1343910e-03, ...,
         3.5174916e-04, -9.9915051e-01, -7.5816858e-01]], dtype=float32)

'初始state'

(64, 512)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

'逻辑'

(896, 3001)

array([[  0.3890362 ,  -0.825235  ,  -7.3335123 , ...,  -5.2433887 ,
         -2.0094223 ,   4.1051226 ],
       [  1.8353196 ,  -3.3688426 ,  -5.8265133 , ...,  -3.8498738 ,
         -1.868614  ,   4.535734  ],
       [  0.47486326,  -4.431116  ,  -7.656597  , ...,  -4.7251415 ,
         -2.7518206 ,   4.3799653 ],
       ...,
       [  7.735502  ,  12.71295   , -11.42602   , ...,  -3.2191327 ,
         -2.1455696 ,   5.025229  ],
       [ -0.6715446 ,   0.05890182,  -8.282465  , ...,  -3.7530177 ,
         -2.1853254 ,   4.070532  ],
       [  5.640621  ,   5.084725  , -17.959644  , ...,  -8.8376255 ,
         -6.168395  ,   9.651815  ]], dtype=float32)

'最终状态'

(64, 512)

array([[ 2.39459085e+00, -1.95080185e+00, -1.95027947e-01, ...,
         6.95285329e-04, -1.20315105e-01, -8.66162628e-02],
       [ 1.52507639e+00, -1.92951059e+00, -3.99303716e-03, ...,
         1.44839578e-04, -4.26144786e-02, -3.70901451e-02],
       [ 1.67852080e+00, -1.93122721e+00, -4.05135052e-03, ...,
         1.68477884e-04, -3.53038050e-02, -4.80397381e-02],
       ...,
       [ 2.03748488e+00, -9.53484893e-01, -2.65403534e-04, ...,
         2.42490714e-04, -9.99338210e-01, -7.56402731e-01],
       [ 2.39980412e+00, -9.54525054e-01, -3.89187690e-03, ...,
         2.08045487e-04, -9.98932064e-01, -7.57175386e-01],
       [ 1.57792401e+00, -9.52326238e-01, -5.49907796e-04, ...,
         3.51749157e-04, -9.99150515e-01, -7.58168578e-01]], dtype=float32)

'X'

(64, 14)

array([[   2, 1227, 3000,    0, 2252,  253, 1002,    0,  282,   13,  536,
           1,    3, 3000],
       [   2,  745,  485, 2192,  907,    0,  335,   22, 2192,  907,  270,
           1,    3, 3000],
       [   2,  103,   48,  494,  297,    0,  231, 3000, 3000,  527, 1950,
           1,    3, 3000],
       [   2,  667,  431,  256,  907,    0,  279,  411,    4,   19,  329,
           1,    3, 3000],
       [   2,   74, 1085,   24,   38,  157,    0,  224,  166, 3000, 1062,
           1,    3, 3000],
       [   2,  783,   35,  224, 1599, 1007,    0,   29,  140, 3000,  364,
           5,    1,    3],
       [   2,    4,  561,   77,  496,   38,    0,  223,   42,  423,  843,
         943,    1,    3],
       [   2,  301, 1226,  530,  142,  165,    0,  770,  854,  383,  142,
         977,    1,    3],
       [   2,  232, 1222,  748,    4, 1249,    0,  268,  153,  103,  274,
           5,    1,    3],
       [   2, 1761,  964,   64, 1521, 1728,    0, 1766, 1124,  191,  213,
         281,    

'Embedding'

(3001, 128)

array([[-0.61786443, -0.07709629, -0.12532227, ...,  0.5193349 ,
         0.1503872 , -0.12355197],
       [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
         0.23316611, -0.07840608],
       [ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
        -0.10131865,  0.26164633],
       ...,
       [ 0.15059002, -0.2705143 , -0.3868205 , ..., -0.01080665,
        -0.3366271 , -0.03618184],
       [ 0.00977281,  0.0544528 ,  0.00349314, ..., -0.20772688,
         0.2347655 ,  0.15280132],
       [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
         0.23684055,  0.22182734]], dtype=float32)

'Input'

(64, 14, 128)

array([[[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.04087897,  0.30896908,  0.17274971, ..., -0.109882  ,
          0.31141537,  0.05277839],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
          0.23316611, -0.07840608],
        [ 0.9782146 , -0.9526181 , -0.42369497, ..., -0.5015902 ,
         -1.3130728 ,  1.0298895 ],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734]],

       [[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.24687326,  0.03297674,  0.40071034, ..., -0.03007145,
         -0.12745138, -0.00725536],
        [-0.00508994, -0.25352705, -0.17305233, ...,  0.11986811,
         -0.17352395,  0.0735866 ],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  

'Outputs'

(896, 128)

array([[ 2.8821200e-01, -7.7424444e-02,  2.1968849e-03, ...,
         7.7774912e-02, -7.5627065e-01,  6.9714284e-01],
       [ 1.4061834e-04, -1.7498613e-03,  2.0904611e-03, ...,
         2.0755129e-03, -1.7033662e-01, -5.1412087e-02],
       [ 9.4901645e-07, -7.7243305e-05,  6.0190614e-03, ...,
         1.2217755e-01, -5.3384262e-01, -3.6002748e-02],
       ...,
       [ 7.4883407e-01, -9.9319690e-01, -2.6691213e-04, ...,
         2.1271660e-06, -9.3184143e-01, -8.2195550e-01],
       [ 1.7782239e-02, -6.8808764e-01, -6.1757069e-05, ...,
         1.7829709e-05, -9.9378151e-01, -1.4555188e-02],
       [ 7.3021853e-01, -9.8106200e-01, -4.1343910e-03, ...,
         3.5174916e-04, -9.9915051e-01, -7.5816858e-01]], dtype=float32)

'初始state'

(64, 512)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

'逻辑'

(896, 3001)

array([[  0.3890362 ,  -0.825235  ,  -7.3335123 , ...,  -5.2433887 ,
         -2.0094223 ,   4.1051226 ],
       [  1.8353196 ,  -3.3688426 ,  -5.8265133 , ...,  -3.8498738 ,
         -1.868614  ,   4.535734  ],
       [  0.47486326,  -4.431116  ,  -7.656597  , ...,  -4.7251415 ,
         -2.7518206 ,   4.3799653 ],
       ...,
       [  7.735502  ,  12.71295   , -11.42602   , ...,  -3.2191327 ,
         -2.1455696 ,   5.025229  ],
       [ -0.6715446 ,   0.05890182,  -8.282465  , ...,  -3.7530177 ,
         -2.1853254 ,   4.070532  ],
       [  5.640621  ,   5.084725  , -17.959644  , ...,  -8.8376255 ,
         -6.168395  ,   9.651815  ]], dtype=float32)

'最终状态'

(64, 512)

array([[ 2.39459085e+00, -1.95080185e+00, -1.95027947e-01, ...,
         6.95285329e-04, -1.20315105e-01, -8.66162628e-02],
       [ 1.52507639e+00, -1.92951059e+00, -3.99303716e-03, ...,
         1.44839578e-04, -4.26144786e-02, -3.70901451e-02],
       [ 1.67852080e+00, -1.93122721e+00, -4.05135052e-03, ...,
         1.68477884e-04, -3.53038050e-02, -4.80397381e-02],
       ...,
       [ 2.03748488e+00, -9.53484893e-01, -2.65403534e-04, ...,
         2.42490714e-04, -9.99338210e-01, -7.56402731e-01],
       [ 2.39980412e+00, -9.54525054e-01, -3.89187690e-03, ...,
         2.08045487e-04, -9.98932064e-01, -7.57175386e-01],
       [ 1.57792401e+00, -9.52326238e-01, -5.49907796e-04, ...,
         3.51749157e-04, -9.99150515e-01, -7.58168578e-01]], dtype=float32)

'X'

(64, 14)

array([[   2, 1227, 3000,    0, 2252,  253, 1002,    0,  282,   13,  536,
           1,    3, 3000],
       [   2,  745,  485, 2192,  907,    0,  335,   22, 2192,  907,  270,
           1,    3, 3000],
       [   2,  103,   48,  494,  297,    0,  231, 3000, 3000,  527, 1950,
           1,    3, 3000],
       [   2,  667,  431,  256,  907,    0,  279,  411,    4,   19,  329,
           1,    3, 3000],
       [   2,   74, 1085,   24,   38,  157,    0,  224,  166, 3000, 1062,
           1,    3, 3000],
       [   2,  783,   35,  224, 1599, 1007,    0,   29,  140, 3000,  364,
           5,    1,    3],
       [   2,    4,  561,   77,  496,   38,    0,  223,   42,  423,  843,
         943,    1,    3],
       [   2,  301, 1226,  530,  142,  165,    0,  770,  854,  383,  142,
         977,    1,    3],
       [   2,  232, 1222,  748,    4, 1249,    0,  268,  153,  103,  274,
           5,    1,    3],
       [   2, 1761,  964,   64, 1521, 1728,    0, 1766, 1124,  191,  213,
         281,    

'Embedding'

(3001, 128)

array([[-0.61786443, -0.07709629, -0.12532227, ...,  0.5193349 ,
         0.1503872 , -0.12355197],
       [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
         0.23316611, -0.07840608],
       [ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
        -0.10131865,  0.26164633],
       ...,
       [ 0.15059002, -0.2705143 , -0.3868205 , ..., -0.01080665,
        -0.3366271 , -0.03618184],
       [ 0.00977281,  0.0544528 ,  0.00349314, ..., -0.20772688,
         0.2347655 ,  0.15280132],
       [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
         0.23684055,  0.22182734]], dtype=float32)

'Input'

(64, 14, 128)

array([[[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.04087897,  0.30896908,  0.17274971, ..., -0.109882  ,
          0.31141537,  0.05277839],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
          0.23316611, -0.07840608],
        [ 0.9782146 , -0.9526181 , -0.42369497, ..., -0.5015902 ,
         -1.3130728 ,  1.0298895 ],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734]],

       [[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.24687326,  0.03297674,  0.40071034, ..., -0.03007145,
         -0.12745138, -0.00725536],
        [-0.00508994, -0.25352705, -0.17305233, ...,  0.11986811,
         -0.17352395,  0.0735866 ],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  

'Outputs'

(896, 128)

array([[ 2.8821200e-01, -7.7424444e-02,  2.1968849e-03, ...,
         7.7774912e-02, -7.5627065e-01,  6.9714284e-01],
       [ 1.4061834e-04, -1.7498613e-03,  2.0904611e-03, ...,
         2.0755129e-03, -1.7033662e-01, -5.1412087e-02],
       [ 9.4901645e-07, -7.7243305e-05,  6.0190614e-03, ...,
         1.2217755e-01, -5.3384262e-01, -3.6002748e-02],
       ...,
       [ 7.4883407e-01, -9.9319690e-01, -2.6691213e-04, ...,
         2.1271660e-06, -9.3184143e-01, -8.2195550e-01],
       [ 1.7782239e-02, -6.8808764e-01, -6.1757069e-05, ...,
         1.7829709e-05, -9.9378151e-01, -1.4555188e-02],
       [ 7.3021853e-01, -9.8106200e-01, -4.1343910e-03, ...,
         3.5174916e-04, -9.9915051e-01, -7.5816858e-01]], dtype=float32)

'初始state'

(64, 512)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

'逻辑'

(896, 3001)

array([[  0.3890362 ,  -0.825235  ,  -7.3335123 , ...,  -5.2433887 ,
         -2.0094223 ,   4.1051226 ],
       [  1.8353196 ,  -3.3688426 ,  -5.8265133 , ...,  -3.8498738 ,
         -1.868614  ,   4.535734  ],
       [  0.47486326,  -4.431116  ,  -7.656597  , ...,  -4.7251415 ,
         -2.7518206 ,   4.3799653 ],
       ...,
       [  7.735502  ,  12.71295   , -11.42602   , ...,  -3.2191327 ,
         -2.1455696 ,   5.025229  ],
       [ -0.6715446 ,   0.05890182,  -8.282465  , ...,  -3.7530177 ,
         -2.1853254 ,   4.070532  ],
       [  5.640621  ,   5.084725  , -17.959644  , ...,  -8.8376255 ,
         -6.168395  ,   9.651815  ]], dtype=float32)

'最终状态'

(64, 512)

array([[ 2.39459085e+00, -1.95080185e+00, -1.95027947e-01, ...,
         6.95285329e-04, -1.20315105e-01, -8.66162628e-02],
       [ 1.52507639e+00, -1.92951059e+00, -3.99303716e-03, ...,
         1.44839578e-04, -4.26144786e-02, -3.70901451e-02],
       [ 1.67852080e+00, -1.93122721e+00, -4.05135052e-03, ...,
         1.68477884e-04, -3.53038050e-02, -4.80397381e-02],
       ...,
       [ 2.03748488e+00, -9.53484893e-01, -2.65403534e-04, ...,
         2.42490714e-04, -9.99338210e-01, -7.56402731e-01],
       [ 2.39980412e+00, -9.54525054e-01, -3.89187690e-03, ...,
         2.08045487e-04, -9.98932064e-01, -7.57175386e-01],
       [ 1.57792401e+00, -9.52326238e-01, -5.49907796e-04, ...,
         3.51749157e-04, -9.99150515e-01, -7.58168578e-01]], dtype=float32)

'X'

(64, 14)

array([[   2, 1227, 3000,    0, 2252,  253, 1002,    0,  282,   13,  536,
           1,    3, 3000],
       [   2,  745,  485, 2192,  907,    0,  335,   22, 2192,  907,  270,
           1,    3, 3000],
       [   2,  103,   48,  494,  297,    0,  231, 3000, 3000,  527, 1950,
           1,    3, 3000],
       [   2,  667,  431,  256,  907,    0,  279,  411,    4,   19,  329,
           1,    3, 3000],
       [   2,   74, 1085,   24,   38,  157,    0,  224,  166, 3000, 1062,
           1,    3, 3000],
       [   2,  783,   35,  224, 1599, 1007,    0,   29,  140, 3000,  364,
           5,    1,    3],
       [   2,    4,  561,   77,  496,   38,    0,  223,   42,  423,  843,
         943,    1,    3],
       [   2,  301, 1226,  530,  142,  165,    0,  770,  854,  383,  142,
         977,    1,    3],
       [   2,  232, 1222,  748,    4, 1249,    0,  268,  153,  103,  274,
           5,    1,    3],
       [   2, 1761,  964,   64, 1521, 1728,    0, 1766, 1124,  191,  213,
         281,    

'Embedding'

(3001, 128)

array([[-0.61786443, -0.07709629, -0.12532227, ...,  0.5193349 ,
         0.1503872 , -0.12355197],
       [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
         0.23316611, -0.07840608],
       [ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
        -0.10131865,  0.26164633],
       ...,
       [ 0.15059002, -0.2705143 , -0.3868205 , ..., -0.01080665,
        -0.3366271 , -0.03618184],
       [ 0.00977281,  0.0544528 ,  0.00349314, ..., -0.20772688,
         0.2347655 ,  0.15280132],
       [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
         0.23684055,  0.22182734]], dtype=float32)

'Input'

(64, 14, 128)

array([[[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.04087897,  0.30896908,  0.17274971, ..., -0.109882  ,
          0.31141537,  0.05277839],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  0.471165  ,
          0.23316611, -0.07840608],
        [ 0.9782146 , -0.9526181 , -0.42369497, ..., -0.5015902 ,
         -1.3130728 ,  1.0298895 ],
        [ 0.06548055, -0.1559302 , -0.07130487, ..., -0.05064205,
          0.23684055,  0.22182734]],

       [[ 0.18300349, -0.09077186, -0.1842504 , ...,  0.13527504,
         -0.10131865,  0.26164633],
        [ 0.24687326,  0.03297674,  0.40071034, ..., -0.03007145,
         -0.12745138, -0.00725536],
        [-0.00508994, -0.25352705, -0.17305233, ...,  0.11986811,
         -0.17352395,  0.0735866 ],
        ...,
        [-0.14115623, -0.63883716,  0.6511718 , ...,  

'Outputs'

(896, 128)

array([[ 2.8821200e-01, -7.7424444e-02,  2.1968849e-03, ...,
         7.7774912e-02, -7.5627065e-01,  6.9714284e-01],
       [ 1.4061834e-04, -1.7498613e-03,  2.0904611e-03, ...,
         2.0755129e-03, -1.7033662e-01, -5.1412087e-02],
       [ 9.4901645e-07, -7.7243305e-05,  6.0190614e-03, ...,
         1.2217755e-01, -5.3384262e-01, -3.6002748e-02],
       ...,
       [ 7.4883407e-01, -9.9319690e-01, -2.6691213e-04, ...,
         2.1271660e-06, -9.3184143e-01, -8.2195550e-01],
       [ 1.7782239e-02, -6.8808764e-01, -6.1757069e-05, ...,
         1.7829709e-05, -9.9378151e-01, -1.4555188e-02],
       [ 7.3021853e-01, -9.8106200e-01, -4.1343910e-03, ...,
         3.5174916e-04, -9.9915051e-01, -7.5816858e-01]], dtype=float32)

'初始state'

(64, 512)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

'逻辑'

(896, 3001)

array([[  0.3890362 ,  -0.825235  ,  -7.3335123 , ...,  -5.2433887 ,
         -2.0094223 ,   4.1051226 ],
       [  1.8353196 ,  -3.3688426 ,  -5.8265133 , ...,  -3.8498738 ,
         -1.868614  ,   4.535734  ],
       [  0.47486326,  -4.431116  ,  -7.656597  , ...,  -4.7251415 ,
         -2.7518206 ,   4.3799653 ],
       ...,
       [  7.735502  ,  12.71295   , -11.42602   , ...,  -3.2191327 ,
         -2.1455696 ,   5.025229  ],
       [ -0.6715446 ,   0.05890182,  -8.282465  , ...,  -3.7530177 ,
         -2.1853254 ,   4.070532  ],
       [  5.640621  ,   5.084725  , -17.959644  , ...,  -8.8376255 ,
         -6.168395  ,   9.651815  ]], dtype=float32)

'最终状态'

(64, 512)

array([[ 2.39459085e+00, -1.95080185e+00, -1.95027947e-01, ...,
         6.95285329e-04, -1.20315105e-01, -8.66162628e-02],
       [ 1.52507639e+00, -1.92951059e+00, -3.99303716e-03, ...,
         1.44839578e-04, -4.26144786e-02, -3.70901451e-02],
       [ 1.67852080e+00, -1.93122721e+00, -4.05135052e-03, ...,
         1.68477884e-04, -3.53038050e-02, -4.80397381e-02],
       ...,
       [ 2.03748488e+00, -9.53484893e-01, -2.65403534e-04, ...,
         2.42490714e-04, -9.99338210e-01, -7.56402731e-01],
       [ 2.39980412e+00, -9.54525054e-01, -3.89187690e-03, ...,
         2.08045487e-04, -9.98932064e-01, -7.57175386e-01],
       [ 1.57792401e+00, -9.52326238e-01, -5.49907796e-04, ...,
         3.51749157e-04, -9.99150515e-01, -7.58168578e-01]], dtype=float32)


None


In [44]:
help(tf.nn.embedding_lookup)

Help on function embedding_lookup in module tensorflow.python.ops.embedding_ops:

embedding_lookup(params, ids, partition_strategy='mod', name=None, validate_indices=True, max_norm=None)
    Looks up `ids` in a list of embedding tensors.
    
    This function is used to perform parallel lookups on the list of
    tensors in `params`.  It is a generalization of
    @{tf.gather}, where `params` is
    interpreted as a partitioning of a large embedding tensor.  `params` may be
    a `PartitionedVariable` as returned by using `tf.get_variable()` with a
    partitioner.
    
    If `len(params) > 1`, each element `id` of `ids` is partitioned between
    the elements of `params` according to the `partition_strategy`.
    In all strategies, if the id space does not evenly divide the number of
    partitions, each of the first `(max_id + 1) % len(params)` partitions will
    be assigned one more id.
    
    If `partition_strategy` is `"mod"`, we assign each id to partition
    `p = id % len(

In [10]:
help(tf.get_variable)

Help on function get_variable in module tensorflow.python.ops.variable_scope:

get_variable(name, shape=None, dtype=None, initializer=None, regularizer=None, trainable=True, collections=None, caching_device=None, partitioner=None, validate_shape=True, use_resource=None, custom_getter=None, constraint=None)
    Gets an existing variable with these parameters or create a new one.
    
    This function prefixes the name with the current variable scope
    and performs reuse checks. See the
    @{$variables$Variable Scope How To}
    for an extensive description of how reusing works. Here is a basic example:
    
    ```python
    def foo():
      with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
        v = tf.get_variable("v", [1])
      return v
    
    v1 = foo()  # Creates v.
    v2 = foo()  # Gets the same, existing v.
    assert v1 == v2
    ```
    
    If initializer is `None` (the default), the default initializer passed in
    the variable scope will be used. If that one is 