In [1]:
%run train.py --cell_type "lstm"


Parameters:
ALLOW_SOFT_PLACEMENT = <absl.flags._flag.BooleanFlag object at 0x7f3e322d4a58>
BATCH_SIZE = <absl.flags._flag.Flag object at 0x7f3e322d4630>
CELL_TYPE = <absl.flags._flag.Flag object at 0x7f3e322d42b0>
CHECKPOINT_EVERY = <absl.flags._flag.Flag object at 0x7f3e322d48d0>
DEV_SAMPLE_PERCENTAGE = <absl.flags._flag.Flag object at 0x7f3e322d4048>
DISPLAY_EVERY = <absl.flags._flag.Flag object at 0x7f3e322d4780>
DROPOUT_KEEP_PROB = <absl.flags._flag.Flag object at 0x7f3e322d44e0>
EMBEDDING_DIM = <absl.flags._flag.Flag object at 0x7f3e322d4390>
EVALUATE_EVERY = <absl.flags._flag.Flag object at 0x7f3e322d4828>
HIDDEN_SIZE = <absl.flags._flag.Flag object at 0x7f3e322d4438>
L2_REG_LAMBDA = <absl.flags._flag.Flag object at 0x7f3e322d4588>
LEARNING_RATE = <absl.flags._flag.Flag object at 0x7f3e322d4a20>
LOG_DEVICE_PLACEMENT = <absl.flags._flag.BooleanFlag object at 0x7f3e322d4b70>
MAX_SENTENCE_LENGTH = <absl.flags._flag.Flag object at 0x7f3e322d4208>
NEG_DIR = <absl.flags._flag.Flag obj

/home/rollo/tensorflow/lib/python3.4/site-packages/tensorflow/python/ops/gradients_impl.py:98: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Writing to /var/www/html/test/py/py_study/NLP2/runs/1544517516

2018-12-11T16:38:40.981585: step 10, loss 5.86946, acc 0.53125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-10

2018-12-11T16:38:44.126264: step 20, loss 5.13909, acc 0.515625
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-20

2018-12-11T16:38:47.089619: step 30, loss 4.56243, acc 0.484375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-30

2018-12-11T16:38:50.449999: step 40, loss 3.97189, acc 0.59375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-40

2018-12-11T16:38:54.981429: step 50, loss 3.43372, acc 0.65625
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-50

2018-12-11T16:38:58.301366: step 60, loss 3.10267, acc 0.5
Saved model checkpoint to /var/www/html/test/py/py_study/NLP

2018-12-11T16:41:15.784094: step 490, loss 0.502337, acc 0.8125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-490

2018-12-11T16:41:18.772775: step 500, loss 0.284585, acc 0.9375

Evaluation:
2018-12-11T16:41:20.636286: step 500, loss 0.664043, acc 0.722326

Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-500

2018-12-11T16:41:24.053062: step 510, loss 0.322408, acc 0.953125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-510

2018-12-11T16:41:27.151441: step 520, loss 0.375046, acc 0.875
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-520

2018-12-11T16:41:30.100910: step 530, loss 0.409359, acc 0.859375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-530

2018-12-11T16:41:33.094852: step 540, loss 0.37451, acc 0.890625
Saved model checkpoint to /

2018-12-11T16:43:49.459095: step 960, loss 0.260541, acc 0.953125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-960

2018-12-11T16:43:52.391288: step 970, loss 0.346554, acc 0.9375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-970

2018-12-11T16:43:55.346770: step 980, loss 0.314151, acc 0.90625
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-980

2018-12-11T16:43:58.463372: step 990, loss 0.178267, acc 0.984375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-990

2018-12-11T16:44:01.349369: step 1000, loss 0.351029, acc 0.90625

Evaluation:
2018-12-11T16:44:02.581053: step 1000, loss 0.703135, acc 0.738274

Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1000

2018-12-11T16:44:05.548461: step 1010, loss 0.250076, acc 0.9375
Saved model checkpoin

2018-12-11T16:46:21.879255: step 1430, loss 0.148919, acc 1
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1430

2018-12-11T16:46:25.794650: step 1440, loss 0.259752, acc 0.953125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1440

2018-12-11T16:46:29.416212: step 1450, loss 0.158512, acc 1
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1450

2018-12-11T16:46:32.573464: step 1460, loss 0.243001, acc 0.953125
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1460

2018-12-11T16:46:35.377788: step 1470, loss 0.209448, acc 0.984375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1470

2018-12-11T16:46:39.112973: step 1480, loss 0.177063, acc 0.984375
Saved model checkpoint to /var/www/html/test/py/py_study/NLP2/runs/1544517516/checkpoints/model-1480



In [1]:
import tensorflow as tf
import numpy as np
import os
import datetime
import time
from rnn import RNN
import data_helpers

In [2]:
help( tf.contrib.learn.preprocessing.VocabularyProcessor)

Help on class VocabularyProcessor in module tensorflow.contrib.learn.python.learn.preprocessing.text:

class VocabularyProcessor(builtins.object)
 |  Maps documents to sequences of word ids.
 |  
 |  Methods defined here:
 |  
 |  __init__(self, max_document_length, min_frequency=0, vocabulary=None, tokenizer_fn=None)
 |      Initializes a VocabularyProcessor instance.
 |      
 |      Args:
 |        max_document_length: Maximum length of documents.
 |          if documents are longer, they will be trimmed, if shorter - padded.
 |        min_frequency: Minimum frequency of words in the vocabulary.
 |        vocabulary: CategoricalVocabulary object.
 |      
 |      Attributes:
 |        vocabulary_: CategoricalVocabulary object.
 |  
 |  fit(self, raw_documents, unused_y=None)
 |      Learn a vocabulary dictionary of all tokens in the raw documents.
 |      
 |      Args:
 |        raw_documents: An iterable which yield either str or unicode.
 |        unused_y: to match fit format si

In [1]:
%run train.py --cell_type "lstm"


Parameters:
ALLOW_SOFT_PLACEMENT = <absl.flags._flag.BooleanFlag object at 0x7f12d960ca20>
BATCH_SIZE = <absl.flags._flag.Flag object at 0x7f12d960c5f8>
CELL_TYPE = <absl.flags._flag.Flag object at 0x7f12d960c278>
CHECKPOINT_EVERY = <absl.flags._flag.Flag object at 0x7f12d960c898>
DEV_SAMPLE_PERCENTAGE = <absl.flags._flag.Flag object at 0x7f12d960c0f0>
DISPLAY_EVERY = <absl.flags._flag.Flag object at 0x7f12d960c748>
DROPOUT_KEEP_PROB = <absl.flags._flag.Flag object at 0x7f12d960c4a8>
EMBEDDING_DIM = <absl.flags._flag.Flag object at 0x7f12d960c358>
EVALUATE_EVERY = <absl.flags._flag.Flag object at 0x7f12d960c7f0>
HIDDEN_SIZE = <absl.flags._flag.Flag object at 0x7f12d960c400>
L2_REG_LAMBDA = <absl.flags._flag.Flag object at 0x7f12d960c550>
LEARNING_RATE = <absl.flags._flag.Flag object at 0x7f12d960c9e8>
LOG_DEVICE_PLACEMENT = <absl.flags._flag.BooleanFlag object at 0x7f12d960cb38>
MAX_SENTENCE_LENGTH = <absl.flags._flag.Flag object at 0x7f12d960c1d0>
NEG_DIR = <absl.flags._flag.Flag obj

array([[4719,   59,  182, ...,    0,    0,    0],
       [ 129, 7044,  284, ...,    0,    0,    0],
       [ 146,    3,  453, ...,    0,    0,    0],
       ...,
       [6206,    1, 5117, ...,    0,    0,    0],
       [   1, 1884,   34, ...,    0,    0,    0],
       [1689, 1694,   75, ...,    0,    0,    0]])

In [9]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6])
    
    >>> np.random.permutation([1, 4, 9, 12, 15])
    array([15,  1,  9,  4, 12])
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.permutation(arr)
    array([[6, 7, 8],
           [0, 1, 2],
           [3, 4, 5]])

