In [54]:
import numpy as np
import tensorflow as tf
sess = tf.Session()

In [35]:
LSTM_CELL_SIZE = 4  # 输出尺寸（维度），与单元格中的隐藏尺寸相同

lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)
state = (tf.zeros([2,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor 'zeros_4:0' shape=(2, 4) dtype=float32>,
 <tf.Tensor 'zeros_4:0' shape=(2, 4) dtype=float32>)

In [36]:
sample_input = tf.constant([[1,2,3,4,3,2],[3,2,2,2,2,2]],dtype=tf.float32)
print (sess.run(sample_input))

[[1. 2. 3. 4. 3. 2.]
 [3. 2. 2. 2. 2. 2.]]


In [37]:
with tf.variable_scope("LSTM_sample3"):
    output, state_new = lstm_cell(sample_input, state)
sess.run(tf.global_variables_initializer())
print (sess.run(state_new))

LSTMStateTuple(c=array([[-0.43529567,  0.03958813,  0.8070472 ,  0.52889174],
       [ 0.20931017,  0.1332616 , -0.60053825,  0.25247544]],
      dtype=float32), h=array([[-0.14358418,  0.00666821,  0.32217664,  0.07481965],
       [ 0.14165983,  0.01227455, -0.42908242,  0.08851139]],
      dtype=float32))


In [38]:
help(tf.contrib.rnn.BasicLSTMCell)

Help on class BasicLSTMCell in module tensorflow.python.ops.rnn_cell_impl:

class BasicLSTMCell(_LayerRNNCell)
 |  Basic LSTM recurrent network cell.
 |  
 |  The implementation is based on: http://arxiv.org/abs/1409.2329.
 |  
 |  We add forget_bias (default: 1) to the biases of the forget gate in order to
 |  reduce the scale of forgetting in the beginning of the training.
 |  
 |  It does not allow cell clipping, a projection layer, and does not
 |  use peep-hole connections: it is the basic baseline.
 |  
 |  For advanced models, please use the full @{tf.nn.rnn_cell.LSTMCell}
 |  that follows.
 |  
 |  Method resolution order:
 |      BasicLSTMCell
 |      _LayerRNNCell
 |      RNNCell
 |      tensorflow.python.layers.base.Layer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num_units, forget_bias=1.0, state_is_tuple=True, activation=None, reuse=None, name=None)
 |      Initialize the basic LSTM cell.
 |      
 |      Args:
 |        num_units: int, 

In [58]:
# 堆叠LSTM
sess = tf.Session()
LSTM_CELL_SIZE = 4  # 输出尺寸（维度），与单元格中的隐藏尺寸相同 
input_dim = 6        
num_layers = 3

In [59]:
cells = []
for _ in range(num_layers):
    cell = tf.contrib.rnn.LSTMCell(LSTM_CELL_SIZE,)
    cells.append(cell)
stacked_lstm = tf.contrib.rnn.MultiRNNCell(cells)

In [61]:
data = tf.placeholder(tf.float32, [None, None, input_dim])
output, state = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)

sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],
                [[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],
                [[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]

In [62]:
sess.run(tf.global_variables_initializer())
sess.run(output, feed_dict={data: sample_input})

array([[[ 0.13624077,  0.13096371,  0.12722576,  0.00196907],
        [ 0.04306107,  0.22711045,  0.22253367, -0.06120773],
        [ 0.05338787,  0.2632047 ,  0.23139995, -0.02738318]],

       [[ 0.13624077,  0.13096371,  0.12722576,  0.00196907],
        [ 0.04306107,  0.22711045,  0.22253367, -0.06120773],
        [ 0.05338787,  0.2632047 ,  0.23139995, -0.02738318]],

       [[ 0.13624077,  0.13096371,  0.12722576,  0.00196907],
        [ 0.1279214 ,  0.19765474,  0.2838099 ,  0.00835462],
        [-0.08375914,  0.2291002 ,  0.35174415, -0.09680846]]],
      dtype=float32)